### ISSUE TITLE
application namespaces

### ISSUE THREAD

**Issue by mhaddon** [filipprosovsky/argocd-image-updater-multiple-sources#1]
I see you guys have added code to support application namespaces, I have built your container, and added the following to my args:
- --app-namespaces="main-namespace,other-namespace"

I have also created a role:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-image-updater
  namespace: other-namespace
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
      - list
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-image-updater
  namespace: other-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-image-updater
subjects:
  - kind: ServiceAccount
    name: argocd-image-updater
    namespace: main-namespace
```

any idea why i would be getting an error like this still: https://github.com/argoproj-labs/argocd-image-updater/issues/352

[edit]

ah it needs to be: `- --app-namespaces=main-namespace,other-namespace`

got another issue, but looking

**Comment by filipprosovsky** [comment]
yep correct, if you use extraArgs in helm-chart, key and value needs to be in separate lines

**Comment by mhaddon** [comment]
I am hitting this stack-trace:

```
time="2023-08-01T21:15:22Z" level=info msg="Successfully updated image 'redacted/static-site' to 'redacted/static-site:2023-07-30--01-28-24--p5VZEMKbcnRQ', but pending spec update (dry run=false)" alias=staticsite application=prod-video-render image_name=static-site image_tag= registry=redacted
time="2023-08-01T21:15:22Z" level=debug msg="Using commit message: build: automatic update of prod-video-render\n\nupdates image render tag '' to '2023-07-30--01-33-12--wsV6xsD8IS7t'\nupdates image static-site tag '' to '2023-07-30--01-28-24--p5VZEMKbcnRQ'\n"
time="2023-08-01T21:15:22Z" level=info msg="Committing 2 parameter update(s) for application prod-video-render" application=prod-video-render
time="2023-08-01T21:15:29Z" level=info msg=Trace args="[git fetch origin --tags --force]" dir=/tmp/git-prod-frontend3285622257 operation_name="exec git" time_ms=7343.335714
time="2023-08-01T21:15:29Z" level=info msg="git config user.name argocd-image-updater" dir=/tmp/git-prod-frontend3285622257 execID=eca60
time="2023-08-01T21:15:29Z" level=info msg=Trace args="[git config user.name argocd-image-updater]" dir=/tmp/git-prod-frontend3285622257 operation_name="exec git" time_ms=0.570466
time="2023-08-01T21:15:29Z" level=info msg="git config user.email noreply@argoproj.io" dir=/tmp/git-prod-frontend3285622257 execID=782df
time="2023-08-01T21:15:29Z" level=info msg=Trace args="[git config user.email noreply@argoproj.io]" dir=/tmp/git-prod-frontend3285622257 operation_name="exec git" time_ms=0.584324
time="2023-08-01T21:15:29Z" level=info msg="git checkout --force master" dir=/tmp/git-prod-frontend3285622257 execID=63ada
time="2023-08-01T21:15:30Z" level=info msg=Trace args="[git checkout --force master]" dir=/tmp/git-prod-frontend3285622257 operation_name="exec git" time_ms=786.686561
time="2023-08-01T21:15:30Z" level=info msg="git submodule update --init --recursive" dir=/tmp/git-prod-frontend3285622257 execID=d4146
time="2023-08-01T21:15:31Z" level=info msg=Trace args="[git submodule update --init --recursive]" dir=/tmp/git-prod-frontend3285622257 operation_name="exec git" time_ms=896.251905
time="2023-08-01T21:15:31Z" level=info msg="git clean -fdx" dir=/tmp/git-prod-frontend3285622257 execID=036c0
time="2023-08-01T21:15:31Z" level=info msg=Trace args="[git clean -fdx]" dir=/tmp/git-prod-frontend3285622257 operation_name="exec git" time_ms=3.188083
time="2023-08-01T21:15:31Z" level=warning msg="Source type2 ='Helm'"
time="2023-08-01T21:15:31Z" level=warning msg="Source type ='Helm'"
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 267 [running]:
github.com/argoproj-labs/argocd-image-updater/pkg/argocd.writeOverrides(0xc000600c00, 0xc000ff4210, {0x290eca0, 0xc000b3f490})
	/src/argocd-image-updater/pkg/argocd/git.go:291 +0x57c
github.com/argoproj-labs/argocd-image-updater/pkg/argocd.commitChangesGit(0xc000600c00, 0xc000ff4210, {0xc0006364f8, 0x1, 0x1}, 0x26bc560)
	/src/argocd-image-updater/pkg/argocd/git.go:215 +0x7e9
github.com/argoproj-labs/argocd-image-updater/pkg/argocd.commitChanges(0xc00032ad30?, 0xc0008c2340?, {0xc0006364f8?, 0xc00028f7f0?, 0xc000df16a0?})
	/src/argocd-image-updater/pkg/argocd/update.go:544 +0x5b
github.com/argoproj-labs/argocd-image-updater/pkg/argocd.commitChangesLocked(0xc000f44b80?, 0xc000ff4210?, 0x34?, {0xc0006364f8?, 0x1?, 0x1?})
	/src/argocd-image-updater/pkg/argocd/update.go:524 +0x110
github.com/argoproj-labs/argocd-image-updater/pkg/argocd.UpdateApplication(0xc00055bb98, 0x19?)
	/src/argocd-image-updater/pkg/argocd/update.go:329 +0x1f2d
main.runImageUpdater.func1({_, _}, {{{{0xc0008ae860, 0xb}, {0xc00021a9c0, 0x14}}, {{0xc0008ae8d0, 0xd}, {0x0, 0x0}, ...}, ...}, ...})
	/src/argocd-image-updater/cmd/run.go:320 +0x287
created by main.runImageUpdater
	/src/argocd-image-updater/cmd/run.go:306 +0xbbd
```

**Comment by filipprosovsky** [comment]
Did you built it with the current commit of adding yaml.v3 ?

**Comment by mhaddon** [comment]
Yes, I will try reverting to the previous commit and try that

**Comment by filipprosovsky** [comment]
I see, you are using `source` instead of `sources` as we do. Did not really test that scenario :/ 
By any chance you using Kustomize? Cause we commented out:
`	// case ApplicationTypeKustomize:
	// 	if app.Spec.GetSource().Kustomize == nil {
	// 		return nil, nil
	// 	}
	// 	params := kustomizeOverride{
	// 		Kustomize: kustomizeImages{
	// 			Images: &app.Spec.GetSource().Kustomize.Images,
	// 		},
	// 	}
	// 	override, err = yaml.Marshal(params)`

**Comment by mhaddon** [comment]
I am using Helm, I was being cheeky and seeing if I could use your application-namespaces code without using the multiple sources part.

My application looks like this:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "asset-proxy"
  namespace: {{ .Release.Namespace | quote }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git:secret:mynamespace/argocd-image-updater-creds
    argocd-image-updater.argoproj.io/git-branch: mybranch
    argocd-image-updater.argoproj.io/image-list: proxy=redacted/asset-proxy
    argocd-image-updater.argoproj.io/proxy.update-strategy: latest
    argocd-image-updater.argoproj.io/proxy.force-update: "true"
    argocd-image-updater.argoproj.io/proxy.helm.image-name: proxy.image.name
    argocd-image-updater.argoproj.io/proxy.helm.image-tag: proxy.image.tag
  labels:
    env: myenvironment
spec:
  destination:
    namespace: mynamespace
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: myrepourl
    path: mypath
    targetRevision: mybranch
    helm:
      passCredentials: true
      values: |
        myvalues: 1
      valueFiles:
        - .argocd-source-myenvironment.yaml
  project: mynamespace
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
```

**Comment by filipprosovsky** [comment]
For multiple sources, you can use ref values like:
```
  sources:
    - repoURL: <YOUR_GIT_REPO> # for helm repo, you would need to use annotation to specify git-repo
      targetRevision: <revision>
      path: <path for image updater file>
      helm:
        ignoreMissingValueFiles: true
        valueFiles:
          - $values/{{ .Values.global.environment_name }}/apps/image-updater/.argocd-source-{{ $chartName }}.yaml
    - repoURL: <YOUR-GIT-REPO>
      targetRevision: <BRANCH>
      ref: values
```
